name: Build and Deploy to FTP

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build
      env:
        CI: false

    - name: Deploy using FTP
      run: |
        echo "open $FTP_HOST" > ftp_commands.txt
        echo "user $FTP_USERNAME $FTP_PASSWORD" >> ftp_commands.txt
        echo "cd /www" >> ftp_commands.txt
        echo "lcd build" >> ftp_commands.txt
        echo "prompt" >> ftp_commands.txt
        echo "binary" >> ftp_commands.txt

        # Ajoutez les fichiers à transférer
        find build -type f | sed "s|build/||" | sed -e "s/^/put /" >> ftp_commands.txt

        # Ajoutez les dossiers à créer
        find build -type d | sed "s|build/||" | sed -e "s/^/mkdir -p /" -e "s/$//" | sort -r >> ftp_commands.txt

        echo "bye" >> ftp_commands.txt

        ftp -inv < ftp_commands.txt
      env:
        FTP_HOST: ${{ secrets.FTP_HOST }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
